#ifndef _9FOLDSCRIPTING_GLOBAL_H
#define _9FOLDSCRIPTING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(_9FOLDSCRIPTING_LIBRARY)
#  define _9FOLDSCRIPTINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define _9FOLDSCRIPTINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // _9FOLDSCRIPTING_GLOBAL_H
