#ifndef _9FOLDSCENE_GLOBAL_H
#define _9FOLDSCENE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(_9FOLDSCENE_LIBRARY)
#  define _9FOLDSCENESHARED_EXPORT Q_DECL_EXPORT
#else
#  define _9FOLDSCENESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // _9FOLDSCENE_GLOBAL_H
