#ifndef _9FOLDPYTHON_GLOBAL_H
#define _9FOLDPYTHON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(_9FOLDPYTHON_LIBRARY)
#  define _9FOLDPYTHONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define _9FOLDPYTHONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // _9FOLDPYTHON_GLOBAL_H
