#ifndef _9FOLDGEOMETRY_GLOBAL_H
#define _9FOLDGEOMETRY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(_9FOLDGEOMETRY_LIBRARY)
#  define _9FOLDGEOMETRYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define _9FOLDGEOMETRYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // _9FOLDGEOMETRY_GLOBAL_H
