#ifndef _9FOLDWIDGETS_GLOBAL_H
#define _9FOLDWIDGETS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(_9FOLDWIDGETS_LIBRARY)
#  define _9FOLDWIDGETSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define _9FOLDWIDGETSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // _9FOLDWIDGETS_GLOBAL_H
