#ifndef _9FOLDMULTIMEDIA_GLOBAL_H
#define _9FOLDMULTIMEDIA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(_9FOLDMULTIMEDIA_LIBRARY)
#  define _9FOLDMULTIMEDIASHARED_EXPORT Q_DECL_EXPORT
#else
#  define _9FOLDMULTIMEDIASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // 9FOLDMULTIMEDIA_GLOBAL_H
